/**
 * Calculates the complementary error function erfc(x).
 * Using numerical approximation. Maximum error: 1.2 * 10^-7
 */
export function erfc(x: number): number {
    const z = Math.abs(x);
    const t = 1.0 / (1.0 + 0.5 * z);
    const r = t * Math.exp(-z * z - 1.26551223 +
        t * (1.00002368 +
            t * (0.37409196 +
                t * (0.09678418 +
                    t * (-0.18628806 +
                        t * (0.27886807 +
                            t * (-1.13520398 +
                                t * (1.48851587 +
                                    t * (-0.82215223 +
                                        t * (0.17087277))))))))));
    return x >= 0 ? r : 2.0 - r;
}

/**
 * Finite Line Source (FLS) Model
 * Calculates temperature rise Delta T at (r, z) generated by a finite 
 * line source of length H placed at depth D. Uses the mirror image method 
 * to enforce a constant boundary condition Delta T = 0 at z = 0.
 * 
 * @param r - Radial distance from borehole center (m)
 * @param z - Depth from surface (m)
 * @param tSeconds - Time since heat injection started (s)
 * @param q - Heat rejection rate per unit length (W/m)
 * @param k - Soil thermal conductivity (W/mK)
 * @param alpha - Soil thermal diffusivity (m2/s)
 * @param H - Borehole length (m)
 * @param D - Borehole buried depth initially from surface (m)
 * @returns Temperature rise (K)
 */
export function calculateFLS(
    r: number,
    z: number,
    tSeconds: number,
    q: number,
    k: number,
    alpha: number,
    H: number,
    D: number
): number {
    // Prevent singularities directly on the line source by adding a tiny radius offset 
    // (usually assumed to be the borehole radius, e.g. 0.05m)
    const safeR = r < 0.01 ? 0.01 : r;

    // Enforce 0.1m integration step for high precision numerical summation
    const N = Math.max(1, Math.ceil(H / 0.1));
    const dh = H / N;
    let sum = 0;

    const sqrtAlphaT2 = 2 * Math.sqrt(alpha * tSeconds);

    for (let i = 0; i <= N; i++) {
        const h = D + i * dh;
        const weight = (i === 0 || i === N) ? 0.5 : 1.0; // Trapezoidal weights

        // Real heat source influence (located at z = h)
        const d1_sq = safeR * safeR + (z - h) * (z - h);
        const d1 = Math.sqrt(d1_sq);
        const arg1 = d1 / sqrtAlphaT2;
        const term1 = erfc(arg1) / d1;

        // Imaginary (Mirror) heat source influence to act as boundary condition at z=0 
        // (located at z = -h)
        const d2_sq = safeR * safeR + (z + h) * (z + h);
        const d2 = Math.sqrt(d2_sq);
        const arg2 = d2 / sqrtAlphaT2;
        const term2 = erfc(arg2) / d2;

        // Superposition (subtract mirror influence)
        sum += weight * (term1 - term2) * dh;
    }

    return (q / (4 * Math.PI * k)) * sum;
}
